opt_in_rules:
  - conditional_returns_on_newline
  - closure_body_length
  - file_name
  
disabled_rules:
  - identifier_name

large_tuple: 4
function_body_length : 50
function_parameter_count: 9
warning_threshold: 1
file_length: 750

cyclomatic_complexity:
  warning: 6
  ignores_case_statements: true

line_length:
  warning: 120
  ignores_comments: true

nesting:
  type_level: 3

conditional_returns_on_newline:
  if_only: true

file_name:
  prefix_pattern: ""
  suffix_pattern: "(Extension|Theme)?|\\+.*"

custom_rules:
  no_break_with_label:
    regex: "[ ]+break [A-z0-9]+"
    message: "Please, don't use break with label"

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - .swiftpm
  - derivedData
