name: Unit Testing

on:
  push:
    branches-ignore:
        - 'release/**'
  
jobs:
   swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane lint
    - name: Updload to codecov
      run: bash <(curl -s https://codecov.io/bash)
